import Head from "next/head";
import Image from "next/image";
import { ALL_PATHS, POST_BY_SLUG } from "../../libs/queries";
import fetcher from "../../libs/fetcher";

const Post = ({ post }) => {
  const src = post.featuredImage.node.sourceUrl;
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main" style={{ maxWidth: 1000, margin: "0 auto" }}>
        <h1>Blog</h1>
        <h3>{post.title}</h3>
        <Image
          src={src}
          priority
          alt=""
          width={1000}
          height={500}
          objectFit="cover"
        />
        <div dangerouslySetInnerHTML={{ __html: post.content }} />
        <p>{post.date}</p>
      </main>
    </div>
  );
};

export default Post;

export const getStaticPaths = async () => {
  const { data } = await fetcher(ALL_PATHS);

  const paths = data.data.posts.nodes.map((post) => ({
    params: { slug: post.slug },
  }));

  return { paths, fallback: false };
};

export const getStaticProps = async ({ params }) => {
  const { data } = await fetcher(POST_BY_SLUG, {
    id: params.slug,
    idType: "SLUG",
  });
  const post = data.data.post;

  return {
    props: {
      post,
    },
    revalidate: 10,
  };
};
