import Head from "next/head";
import { ALL_POSTS } from "../../libs/queries";
import fetcher from "../../libs/fetcher";
import Link from "next/link";
import Image from "next/image";

const Blog = ({ allPosts = [] }) => {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1>Blog</h1>
        <div className="grid">
          {allPosts.map((post, index) => {
            const src = post.featuredImage?.node.sourceUrl;

            return (
              <Link href={"/blog/" + post.slug} key={post.slug} >
                <a>
                  <div className="card">
                    <h3>{post.title}</h3>

                    <Image
                      priority={index < 2}
                      src={src}
                      alt=""
                      width={500}
                      height={250}
                      objectFit="cover"
                    />
                    <div dangerouslySetInnerHTML={{ __html: post.excerpt }} />
                    <p>{post.date}</p>
                  </div>
                </a>
              </Link>
            );
          })}
        </div>
      </main>
    </div>
  );
};

export default Blog;

export const getStaticProps = async () => {
  const { data } = await fetcher(ALL_POSTS);
  const allPosts = data.data.posts.nodes;

  return {
    props: { allPosts },
    revalidate: 10,
  };
};
